package com.finance_tracker.backend_server.auth.entity;

import com.finance_tracker.backend_server.user.entity.User;
import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

@Entity
@Table(name = "refresh_tokens")
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@Builder
public class RefreshToken {

    /**
     * Unique identifier for the refresh token.
     * Auto-generated by the database using IDENTITY strategy for PostgreSQL compatibility.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The user associated with this refresh token.
     * <p>
     * A one-to-one relationship ensures each user has at most one active refresh token.
     * </p>
     */
    @OneToOne
    @JoinColumn(name = "user_id", referencedColumnName = "id", nullable = false)
    private User user;

    /**
     * The unique token string.
     * <p>
     * Generated as a UUID when the refresh token is created.
     * Used to validate token refresh requests.
     * </p>
     */
    @Column(nullable = false, unique = true)
    private String token;

    /**
     * The expiration timestamp of the refresh token.
     * <p>
     * Tokens are invalid after this time and will be deleted upon verification.
     * </p>
     */
    @Column(nullable = false)
    private Instant expiryDate;
}

