package com.finance_tracker.backend_server.user.entity;

import com.finance_tracker.backend_server.user.entity.enumeration.ERole;
import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "roles")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Role {

    /**
     * Unique identifier for the role.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * The role name from the {@link ERole} enumeration.
     * <p>
     * Stored as a string in the database for better readability.
     * The maximum length is 20 characters.
     * </p>
     */
    @Enumerated(EnumType.STRING)
    @Column(length = 20, unique = true, nullable = false)
    private ERole name;
}