package com.finance_tracker.backend_server.user.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "users",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = "username"),
                @UniqueConstraint(columnNames = "email")
        })
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class User {

    /**
     * Unique identifier for the user.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The unique username for authentication.
     * <p>
     * Must be between 1 and 20 characters.
     * Cannot be blank.
     * </p>
     */
    @NotBlank(message = "Username is required")
    @Size(max = 20, message = "Username must not exceed 20 characters")
    @Column(nullable = false, length = 20)
    private String username;

    /**
     * The user's email address.
     * <p>
     * Must be a valid email format and unique across all users.
     * Maximum length is 50 characters.
     * </p>
     */
    @NotBlank(message = "Email is required")
    @Size(max = 50, message = "Email must not exceed 50 characters")
    @Email(message = "Email must be a valid email address")
    @Column(nullable = false, length = 50)
    private String email;

    /**
     * The user's encoded password.
     * <p>
     * Stored in BCrypt encoded format.
     * Maximum length is 120 characters to accommodate the hash.
     * </p>
     */
    @NotBlank(message = "Password is required")
    @Size(max = 120)
    @Column(nullable = false, length = 120)
    private String password;

    /**
     * The set of roles assigned to this user.
     * <p>
     * Roles are fetched lazily for performance optimization.
     * The relationship is managed through a join table named 'user_roles'.
     * </p>
     */
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(
            name = "user_roles",
            joinColumns = @JoinColumn(name = "user_id"),
            inverseJoinColumns = @JoinColumn(name = "role_id")
    )
    private Set<Role> roles = new HashSet<>();

    /**
     * Constructs a new User with basic credentials.
     * <p>
     * This constructor is typically used during user registration.
     * </p>
     *
     * @param username the unique username
     * @param email the user's email address
     * @param password the encoded password
     */
    public User(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
    }
}

